// Magic Starter Configuration.
//
// This file is auto-generated by the magic_starter install command.
// Customize feature toggles and route prefixes as needed.

import '../app/support/web_links.dart' show WebLinks;

Map<String, dynamic> get magicStarterConfig => {
  'magic_starter': {
    'features': {
      'teams': true,
      'registration': true,
      'extended_profile': true,
      'profile_photos': true,
      'social_login': true,
      'two_factor': true,
      'sessions': true,
      'phone_otp': false,
      'newsletter': true,
      'notifications': true,
      'email_verification': true,
      'guest_auth': false,
      'timezones': true,
      'billing': true,
    },
    'auth': {'email': true, 'phone': false},
    // The absolute origin the hosted checkout redirects back to, and the
    // return target of the billing portal.
    //
    // A fixed constant rather than `Uri.base`, which is not a valid checkout
    // redirect target off the web platform and throws on a non-http(s) scheme
    // (e.g. under `flutter test`'s `file://` origin). The starter deliberately
    // gives this key NO default: Stripe requires an absolute url, so an unset
    // origin would yield a relative one, session creation would fail, and the
    // refusal is written to the log rather than shown to the customer. The
    // checkout call to action is gated on this being set, which is why leaving
    // it out hides the button instead of shipping one that fails on tap.
    'billing': {'web_origin': 'https://uptizm.com'},
    'defaults': {'locale': 'en', 'timezone': 'UTC'},
    'supported_locales': ['en', 'tr'],
    'routes': {
      'home': '/',
      'login': '/auth/login',
      'auth_prefix': '/auth',
      'teams_prefix': '/teams',
      'profile_prefix': '/settings',
      'notifications_prefix': '/notifications',
    },
    // The two website documents the sign-up screen links to. Both were null,
    // which made `MagicStarterConfig.hasLegalLinks()` false and hid the legal
    // line entirely: nobody was shown either document before creating an
    // account. Composed here for the DEFAULT language, because `Magic.init`
    // evaluates this factory before any provider boots and the real locale is
    // not resolved yet; `AppServiceProvider.boot()` re-points both at the
    // active language and keeps them there on every locale change.
    'legal': WebLinks.legalConfig,
  },
};
