import 'package:magic/magic.dart';

import 'uptizm_status_tokens.dart';
import 'wind_theme.g.dart';

// Hand-authored theme-scale supplement.
//
// magic's `design:sync` only emits the colour half of DESIGN.md: the 17
// semantic aliases and the `primary` MaterialColor (see the generated
// `wind_theme.g.dart`, whose only two members are `designAliases` and
// `designColors`). DESIGN.md's `rounded:` and `typography:` blocks reach no
// code at all through that path, so every radius and every font token fell
// back to Wind's built-in defaults, which are NOT uptizm's values.
//
// Two concrete symptoms this file exists to remove:
//
// - Radii rendered at half their specified size. Wind's default scale is
//   `DEFAULT: 4, md: 6, lg: 8`; DESIGN.md declares 8, 12 and 16. Every corner
//   in the app was one step down the wrong scale.
// - The bundled Geist fonts were never used. Wind's default `fontFamilies`
//   holds CSS font STACKS (`'ui-monospace, SFMono-Regular, ...'`), and the
//   text parser assigns that whole string into `TextStyle.fontFamily`, which
//   Flutter resolves as a single registered family name. No such family is
//   registered, so `font-mono` fell through to the platform default and every
//   metric column rendered proportional despite `pubspec.yaml` shipping
//   Geist and Geist Mono as assets.
//
// `WindThemeData` MERGES these maps over its defaults rather than replacing
// them (`wind_theme_data.dart:213-218`), so a key omitted here keeps Wind's
// value. Both maps are still written out in full: the point of the file is
// that a reader can compare it to DESIGN.md line by line.
//
// [buildUptizmWindTheme] at the foot of this file is the single place the app
// theme is assembled, so `lib/main.dart` and the tests that measure the scales
// read the same construction rather than two copies that can drift apart.

/// Corner radii in logical pixels, mirroring DESIGN.md's `rounded:` block.
///
/// `2xl` and `3xl` continue the scale's linear +4 step beyond the five values
/// DESIGN.md originally declared; both are in use in `lib/` (the assistant
/// panel and one avatar), so leaving them on Wind's defaults would have made
/// `2xl` (16) render SMALLER than `xl` (20) once the rest of the scale landed.
/// They were added to DESIGN.md at the same time as this file.
const Map<String, double> uptizmBorderRadius = <String, double>{
  'none': 0.0,
  'sm': 4.0,
  'DEFAULT': 8.0,
  'md': 12.0,
  'lg': 16.0,
  'xl': 20.0,
  '2xl': 24.0,
  '3xl': 32.0,
  'full': 9999.0,
};

/// Font families, mirroring DESIGN.md's `typography:` block.
///
/// Both are the self-hosted variable woff2 files registered in `pubspec.yaml`,
/// not the Google Fonts build (which strips the OpenType feature set that
/// `tabular-nums` needs). The value is a single Flutter family name, never a
/// CSS stack: Flutter matches one registered family and does not fall through
/// a comma-separated list the way a browser does.
///
/// `serif` is deliberately absent, so it keeps Wind's default. Nothing in this
/// app asks for it.
const Map<String, String> uptizmFontFamilies = <String, String>{
  'sans': 'Geist',
  'mono': 'Geist Mono',
};

/// Assembles the app's Wind theme from all four halves of DESIGN.md.
///
/// The colour half (`designColors` + `designAliases`) is generated by
/// `dart run bin/dispatcher.dart design:sync`; the monitoring status families
/// and the two scales above are hand-authored, because design:sync emits
/// neither. Keeping the assembly here rather than inline in `main()` gives the
/// theme one definition that both the app and its tests read.
WindThemeData buildUptizmWindTheme() => WindThemeData(
  colors: designColors,
  aliases: {...designAliases, ...uptizmStatusAliases},
  borderRadius: uptizmBorderRadius,
  fontFamilies: uptizmFontFamilies,
);
