/*
 * Generates the apex host's icon set into public/.
 *
 *   node resources/brand/build-icons.cjs
 *
 * Rerun it whenever the mark or the brand green changes; the outputs are
 * committed so a deploy never has to run a browser. Rendering goes through the
 * same headless Chromium the status-page preview renderer uses, so what lands in
 * a PNG is what a browser actually draws rather than a second rasteriser's
 * interpretation.
 *
 * The geometry is the canonical mark from assets/brand/uptizm-mark.svg: a filled
 * dot inside a ring. It is redrawn here at each size rather than scaled from one
 * master, because the ring's stroke has to be thickened at small sizes or it
 * disappears (the same reason there is a separate uptizm-mark-16.svg).
 */
const fs = require('fs');
const path = require('path');
const puppeteer = require('puppeteer');

const PRIMARY = '#008560';
const SURFACE = '#F9FAFB';

const publicDir = path.join(__dirname, '../../public');
const brandDir = path.join(publicDir, 'brand');

/**
 * The mark as an SVG string.
 *
 * `ringScale` thickens the ring relative to the canvas so it survives at small
 * sizes. `inset` shrinks the drawing inside its box, which is what makes the
 * maskable variant safe: Android may crop up to 20% off every edge, so the mark
 * has to sit inside the middle 60% circle.
 */
const mark = ({ size, ringScale = 1, inset = 0, background = null, ringOpacity = 0.22 }) => {
    const c = size / 2;
    const usable = (size / 2) * (1 - inset);
    const stroke = usable * 0.2 * ringScale;
    const ringRadius = usable * 0.78 - stroke / 2;
    const dotRadius = usable * 0.41;

    return `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 ${size} ${size}">
  ${background ? `<rect width="${size}" height="${size}" fill="${background}"/>` : ''}
  <circle cx="${c}" cy="${c}" r="${ringRadius}" fill="none" stroke="${PRIMARY}" stroke-opacity="${ringOpacity}" stroke-width="${stroke}"/>
  <circle cx="${c}" cy="${c}" r="${dotRadius}" fill="${PRIMARY}"/>
</svg>`;
};

/*
 * The favicon a modern browser prefers. It carries its own dark pair, because a
 * #008560 dot on a dark browser chrome is the one place the light-mode green is
 * too dim to read. This is why the SVG is hand-written rather than generated by
 * the helper above: it needs the media query inside it.
 */
const faviconSvg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16" role="img" aria-label="Uptizm">
  <style>
    .ring { stroke: #008560; }
    .dot { fill: #008560; }
    @media (prefers-color-scheme: dark) {
      .ring { stroke: #00C292; }
      .dot { fill: #00C292; }
    }
  </style>
  <circle class="ring" cx="8" cy="8" r="6.5" fill="none" stroke-opacity="0.42" stroke-width="2"/>
  <circle class="dot" cx="8" cy="8" r="3.4"/>
</svg>`;

/*
 * The social card. 1200x630 is the size every crawler crops to, and the text is
 * baked in because a crawler will not run our CSS. The copy is deliberately the
 * page's own headline: a card promising something the page does not say is the
 * social-preview version of a false claim.
 */
const ogImage = () => `<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <style>
      @font-face {
        font-family: 'Geist';
        src: url('file://${path.join(__dirname, '../fonts/GeistVariable.woff2')}') format('woff2-variations');
        font-weight: 100 900;
      }
      * { margin: 0; padding: 0; box-sizing: border-box; }
      body {
        width: 1200px; height: 630px;
        display: flex; flex-direction: column; justify-content: space-between;
        padding: 80px;
        background: ${SURFACE};
        font-family: 'Geist', sans-serif;
        color: #040608;
      }
      .brand { display: flex; align-items: center; gap: 18px; font-size: 34px; font-weight: 600; letter-spacing: -0.01em; }
      h1 { font-size: 78px; line-height: 1.04; letter-spacing: -0.03em; font-weight: 700; max-width: 15ch; }
      .foot { display: flex; align-items: center; gap: 14px; font-size: 26px; color: #555D65; }
      .pill { font-size: 22px; color: #197037; background: #DCF9E1; border-radius: 999px; padding: 8px 18px; }
    </style>
  </head>
  <body>
    <div class="brand">${mark({ size: 46, ringScale: 1.05 })}<span>Uptizm</span></div>
    <h1>Uptime monitoring that refuses to guess.</h1>
    <!-- No region COUNT in this copy on purpose. The page derives that number
         from the MonitorRegion enum; a baked PNG cannot, so it would silently go
         stale the day a region is added. -->
    <div class="foot">
      <span>HTTP and TCP checks, pinned to the regions you pick</span>
      <span class="pill">uptizm.com</span>
    </div>
  </body>
</html>`;

const png = async (page, html, width, height, out) => {
    await page.setViewport({ width, height, deviceScaleFactor: 1 });
    await page.setContent(html, { waitUntil: 'load' });
    await page.evaluate(() => document.fonts.ready.then(() => true));
    await page.screenshot({ path: out, omitBackground: !html.includes('<rect') && !html.includes('<body') });
    console.log('wrote', path.relative(publicDir, out));
};

(async () => {
    fs.mkdirSync(brandDir, { recursive: true });

    fs.writeFileSync(path.join(publicDir, 'favicon.svg'), faviconSvg + '\n');
    console.log('wrote favicon.svg');

    const browser = await puppeteer.launch({ args: ['--no-sandbox'] });
    const page = await browser.newPage();

    // Transparent PNGs for the PWA icon slots.
    for (const size of [192, 512]) {
        await png(page, mark({ size, ringScale: 1 }), size, size, path.join(brandDir, `icon-${size}.png`));
        await png(
            page,
            mark({ size, ringScale: 1, inset: 0.3, background: SURFACE }),
            size,
            size,
            path.join(brandDir, `icon-maskable-${size}.png`),
        );
    }

    /*
     * Apple's touch icon gets an opaque background on purpose: iOS composites it
     * onto the home screen with no transparency handling, so a transparent PNG
     * turns black behind the mark.
     */
    await png(
        page,
        mark({ size: 180, ringScale: 1, inset: 0.12, background: SURFACE }),
        180,
        180,
        path.join(publicDir, 'apple-touch-icon.png'),
    );

    // The 48px source the .ico is packed from, and the social card.
    await png(page, mark({ size: 48, ringScale: 1.4, ringOpacity: 0.4 }), 48, 48, path.join(brandDir, 'icon-48.png'));
    await png(page, ogImage(), 1200, 630, path.join(brandDir, 'og-image.png'));

    await browser.close();
    console.log('\nNow pack the .ico:  python3 resources/brand/pack-ico.py');
})();
